#include "uart.h"
void putch(unsigned char data) {
    while( ! PIR3bits.TX1IF)          // wait until the transmitter is ready
        continue;
    TX1REG = data;                    // send one character
}

void init_uart(void) {
    TX1STAbits.CSRC = 1;        // Master mode, clock generated by BRG
    TX1STAbits.TX9 = 0;         // 8 bits TX
    TX1STAbits.TXEN = 1;        // TX Enabled
    TX1STAbits.SYNC = 1;        // SYNC mode
    TX1STAbits.SENDB = 0;
    TX1STAbits.BRGH = 1;
    BAUD1CONbits.SCKP = 1;      // Data on raising edge
    BAUD1CONbits.BRG16 = 1;     // 16 bit baud rate counter
    SP1BRG = 8;                 // for 115200 rate, calculated for 64 MHz
}